media:
  - name: images
    label: Images
    input: _site/assets
    output: /assets
    categories: [ image ]

content:
  - name: projects
    label: Projects
    path: _site/projects
    type: collection
    fields: 
      - {name: title, label: title, type: string}
      - {name: author, label: Author, type: string}
      - {name: date, label: Date YYYY-MM-DD, type: string}
      - {name: image, label: image, type: image }
      - {name: imageAlt, label: imageAlt, type: string}
      - {name: description, label: description, type: string, options: { maxLength: 160 } }
      - {name: layout, hidden: true, type: string, default: "article.njk"}
      - {name: body, label: Body, type: rich-text}
  - name: events
    label: Events
    path: _site/events
    type: collection
    fields:
     - {name: title, label: title, type: string}
     - {name: author, label: Author, type: string}
     - {name: date, label: Date YYYY-MM-DD, type: string}
     - {name: image, label: image, type: image }
     - {name: imageAlt, label: imageAlt, type: string}
     - {name: description, label: description, type: string, options: { maxLength: 160 } }
     - {name: layout, hidden: true, type: string, default: "article.njk"}
     - {name: body, label: Body, type: rich-text}
  - name: Home
    label: Home
    path: _site/index.md
    type: file
    fields:
     - {name: Innovators, label: Innovators, type: image}
     - {name: Creators, label: Creators, type: image}
     - {name: Designers, label: Designers, type: image}
     - {name: heroimg, label: Main Image, type: image}
     - {name: layout, hidden: true, type: string, default: "home.njk"}