media:
  - name: eventimgs
    label: Event Images
    input: _site/events/assets
    output: /events/assets
    categories: [ image ]
  - name: projectsimg
    label: Projects Images
    input: _site/projects/assets
    output: /projects/assets
    categories: [ image ]

content:
  - name: projects
    label: Projects
    path: _site/projects
    type: collection
    fields: 
      - {name: title, label: title, type: string}
      - {name: author, label: Author, type: string}
      - {name: date, label: Date, type: date}
      - {name: image, label: image, type: image}
      - {name: imageAlt, label: imageAlt, type: string}
      - {name: description, label: description, type: string, options: { maxLength: 160 } }
      - {name: layout, hidden: true, type: string, default: article.njk}
      - {name: body, label: Body, type: rich-text}
  - name: events
    label: Events
    path: _site/events
    type: collection
    fields:
     - {name: title, label: title, type: string}
     - {name: author, label: Author, type: string}
     - {name: date, label: Date, type: date}
     - {name: image, label: image, type: image}
     - {name: imageAlt, label: imageAlt, type: string}
     - {name: description, label: description, type: string, options: { maxLength: 160 } }
     - {name: layout, hidden: true, type: string, default: article.njk}
     - {name: body, label: Body, type: rich-text}